-- Praxisnaher Materialkatalog fuer deutsche Dachdeckerbetriebe.
-- Nach supabase/schema.sql im Supabase SQL Editor ausfuehren.

insert into public.material_categories (slug, name, sort_order)
values
  ('holz', 'Holz und Unterkonstruktion', 10),
  ('folien', 'Folien und Unterdeckbahnen', 20),
  ('steildach', 'Steildachdeckung', 30),
  ('flachdach', 'Flachdach und Abdichtung', 40),
  ('spenglerei', 'Spenglerei und Entwaesserung', 50),
  ('befestigung', 'Befestigung und Kleinmaterial', 60),
  ('daemmung', 'Daemmung', 70),
  ('chemie', 'Dichtstoffe und Chemie', 80),
  ('dachfenster', 'Dachfenster und Anschluesse', 90),
  ('sicherheit', 'Arbeitsschutz und Sicherheit', 100),
  ('werkzeug', 'Werkzeug und Verbrauch', 110)
on conflict (slug) do update set
  name = excluded.name,
  sort_order = excluded.sort_order,
  active = true;

insert into public.material_subcategories (category_id, slug, name, sort_order)
select c.id, v.slug, v.name, v.sort_order
from (
  values
    ('holz', 'dachlatten', 'Dachlatten', 10),
    ('holz', 'konterlatten', 'Konterlatten', 20),
    ('holz', 'schalung', 'Schalung und Platten', 30),
    ('folien', 'unterdeckbahnen', 'Unterdeckbahnen', 10),
    ('folien', 'dampfbremsen', 'Dampfbremsen', 20),
    ('folien', 'klebebaender', 'Klebebaender', 30),
    ('steildach', 'dachziegel', 'Dachziegel und Dachsteine', 10),
    ('steildach', 'first-grat', 'First und Grat', 20),
    ('steildach', 'zubehoer', 'Steildachzubehoer', 30),
    ('flachdach', 'bitumenbahnen', 'Bitumenbahnen', 10),
    ('flachdach', 'kunststoffbahnen', 'Kunststoffbahnen', 20),
    ('flachdach', 'ablaeufe', 'Dachablaeufe', 30),
    ('flachdach', 'schutzlagen', 'Schutz- und Trennlagen', 40),
    ('spenglerei', 'dachrinne', 'Dachrinnen', 10),
    ('spenglerei', 'fallrohr', 'Fallrohre', 20),
    ('spenglerei', 'bleche', 'Bleche und Profile', 30),
    ('spenglerei', 'anschluesse', 'Anschluesse', 40),
    ('befestigung', 'schrauben', 'Schrauben', 10),
    ('befestigung', 'naegel', 'Naegel', 20),
    ('befestigung', 'klammern', 'Klammern', 30),
    ('befestigung', 'duebel', 'Duebel und Anker', 40),
    ('daemmung', 'mineralwolle', 'Mineralwolle', 10),
    ('daemmung', 'pir-pur', 'PIR und PUR', 20),
    ('daemmung', 'xps-eps', 'XPS und EPS', 30),
    ('chemie', 'dichtstoffe', 'Dichtstoffe', 10),
    ('chemie', 'kleber', 'Kleber', 20),
    ('chemie', 'primer', 'Primer und Voranstrich', 30),
    ('chemie', 'fluessigkunststoff', 'Fluessigkunststoff', 40),
    ('dachfenster', 'fenster', 'Dachfenster', 10),
    ('dachfenster', 'eindeckrahmen', 'Eindeckrahmen', 20),
    ('dachfenster', 'anschlussprodukte', 'Anschlussprodukte', 30),
    ('sicherheit', 'psa', 'Persoenliche Schutzausruestung', 10),
    ('sicherheit', 'absturzsicherung', 'Absturzsicherung', 20),
    ('werkzeug', 'handwerkzeug', 'Handwerkzeug', 10),
    ('werkzeug', 'maschinenzubehoer', 'Maschinenzubehoer', 20),
    ('werkzeug', 'verbrauch', 'Verbrauchsmaterial', 30)
) as v(category_slug, slug, name, sort_order)
join public.material_categories c on c.slug = v.category_slug
on conflict (category_id, slug) do update set
  name = excluded.name,
  sort_order = excluded.sort_order,
  active = true;

with catalog_rows (
  category_slug,
  subcategory_slug,
  name,
  unit,
  package_unit,
  default_minimum_stock,
  short_description,
  search_terms,
  typical_use,
  manufacturer,
  popularity
) as (
  values
    ('holz', 'dachlatten', 'Dachlatte 30 x 50 mm S10 imprraegniert', 'm', 'Bund', 300, 'Standardlatte fuer Steildach-Lattung.', array['dachlatte','latte','30x50','traglatte'], 'Traglattung fuer Dachziegel und Dachsteine', null, 100),
    ('holz', 'dachlatten', 'Dachlatte 40 x 60 mm S10 imprraegniert', 'm', 'Bund', 200, 'Staerkere Latte fuer hoehere Lasten.', array['dachlatte','latte','40x60','traglatte'], 'Traglattung bei groesseren Spannweiten', null, 96),
    ('holz', 'dachlatten', 'Dachlatte 24 x 48 mm roh', 'm', 'Bund', 150, 'Leichte Latte fuer Nebenarbeiten.', array['dachlatte','latte','24x48'], 'Nebenarbeiten und leichte Unterkonstruktionen', null, 74),
    ('holz', 'konterlatten', 'Konterlatte 30 x 50 mm imprraegniert', 'm', 'Bund', 250, 'Konterlattung fuer Hinterlueftung.', array['konterlatte','hinterlueftung','30x50'], 'Belueftungsebene unter der Dachdeckung', null, 98),
    ('holz', 'konterlatten', 'Konterlatte 40 x 60 mm imprraegniert', 'm', 'Bund', 150, 'Robuste Konterlatte fuer Sanierung.', array['konterlatte','40x60','sanierung'], 'Sanierungen und tragfaehige Unterkonstruktion', null, 80),
    ('holz', 'schalung', 'Rauspund 24 mm Nut und Feder', 'm2', 'Paket', 40, 'Schalungsbretter fuer Dachflaechen.', array['rauspund','schalung','nut feder'], 'Dachschalung und Gauben', null, 72),
    ('holz', 'schalung', 'OSB 3 Platte 18 mm', 'm2', 'Paket', 30, 'Feuchtebestaendige Holzwerkstoffplatte.', array['osb','platte','18mm'], 'Schalung und Aussteifung im Dachbereich', null, 70),
    ('holz', 'schalung', 'OSB 3 Platte 22 mm', 'm2', 'Paket', 20, 'Staerkere OSB-Platte fuer belastete Flaechen.', array['osb','platte','22mm'], 'Flachdachaufbauten und Gauben', null, 60),
    ('holz', 'schalung', 'Schalbretter 24 mm sortiert', 'm', 'Bund', 150, 'Klassische Bretter fuer Schalung und Details.', array['schalbrett','brett','schalung'], 'Ortgang, Gaube und Reparatur', null, 66),
    ('holz', 'schalung', 'Keilbohle 40 x 80 mm', 'm', 'Bund', 40, 'Bohle fuer Gefaelle und Anschluesse.', array['keilbohle','bohle','gefaelle'], 'Traufe, Kehle und Anschlussbereiche', null, 52),
    ('holz', 'schalung', 'Bohle 40 x 200 mm', 'm', 'Bund', 30, 'Konstruktionsbohle fuer Dachdetails.', array['bohle','holz','40x200'], 'Dachrand, Aufkantung und Reparatur', null, 48),
    ('holz', 'dachlatten', 'Trauflatte 40 x 60 mm', 'm', 'Bund', 80, 'Latte fuer Traufausbildung.', array['trauflate','traufbohle','latte'], 'Traufdetail und erste Ziegelreihe', null, 64),
    ('holz', 'schalung', 'Fasebrett Fichte 19 mm', 'm2', 'Paket', 20, 'Sichtbrett fuer Untersichten.', array['fasebrett','untersicht','fichte'], 'Dachuntersicht und Bekleidung', null, 46),
    ('holz', 'schalung', 'Glattkantbrett 21 x 95 mm', 'm', 'Bund', 80, 'Brett fuer Ortgang und Detailarbeiten.', array['glattkantbrett','ortgang','brett'], 'Ortgang, Blenden und Reparatur', null, 58),
    ('holz', 'schalung', 'Bauholz Kantholz 60 x 80 mm', 'm', 'Bund', 40, 'Kantholz fuer Hilfskonstruktionen.', array['kantholz','bauholz','60x80'], 'Dachdetails, Aufdoppelung und Abstuetzung', null, 44),

    ('folien', 'unterdeckbahnen', 'Unterspannbahn diffusionsoffen 120 g', 'm2', 'Rolle', 150, 'Standardbahn fuer belueftete Steildaecher.', array['unterspannbahn','usb','diffusionsoffen'], 'Unterdeckung unter Ziegel und Dachstein', null, 100),
    ('folien', 'unterdeckbahnen', 'Unterdeckbahn diffusionsoffen 160 g', 'm2', 'Rolle', 100, 'Robustere Bahn fuer Sanierung.', array['unterdeckbahn','udb','diffusionsoffen'], 'Regensichere Zusatzmassnahme im Steildach', null, 96),
    ('folien', 'unterdeckbahnen', 'Unterdeckbahn selbstklebend 220 g', 'm2', 'Rolle', 75, 'Selbstklebende Bahn fuer erhoehte Anforderungen.', array['unterdeckbahn','selbstklebend','nahtkleber'], 'Sanierung und flach geneigte Daecher', null, 86),
    ('folien', 'unterdeckbahnen', 'Schalungsbahn Bitumen besandet V13', 'm2', 'Rolle', 50, 'Bituminoese Schalungsbahn.', array['schalungsbahn','v13','bitumen'], 'Unterlage auf Holzschalung', null, 70),
    ('folien', 'dampfbremsen', 'Dampfbremse sd variabel', 'm2', 'Rolle', 100, 'Feuchtevariable Luftdichtungsbahn.', array['dampfbremse','sd variabel','luftdicht'], 'Innenliegende Luftdichtung bei Sanierung', null, 78),
    ('folien', 'dampfbremsen', 'Dampfsperre PE 0,2 mm', 'm2', 'Rolle', 100, 'PE-Folie fuer einfache Dampfsperren.', array['dampfsperre','pe folie','folie'], 'Dampfbremsende Ebene im Innenbereich', null, 62),
    ('folien', 'klebebaender', 'Nageldichtband 60 mm', 'm', 'Rolle', 80, 'Dichtband unter Konterlatten.', array['nageldichtband','konterlatte','dichtband'], 'Abdichtung von Nagelstellen', null, 94),
    ('folien', 'klebebaender', 'Systemklebeband Innen 60 mm', 'm', 'Rolle', 80, 'Klebeband fuer Dampfbremsen.', array['klebeband','dampfbremse','innen'], 'Luftdichte Verklebung innen', null, 84),
    ('folien', 'klebebaender', 'Systemklebeband Aussen 60 mm UV-stabil', 'm', 'Rolle', 60, 'Aussenklebeband fuer Unterdeckbahnen.', array['klebeband','aussen','uv'], 'Naht- und Detailverklebung aussen', null, 80),
    ('folien', 'klebebaender', 'Butylband 50 mm', 'm', 'Rolle', 40, 'Butyl-Dichtband fuer Anschluesse.', array['butylband','dichtband','anschluss'], 'Anschluss an Blech, Mauerwerk und Folien', null, 72),
    ('folien', 'klebebaender', 'Anschlusskleber Kartusche', 'Stueck', 'Karton', 12, 'Klebedichtstoff fuer Folienanschluesse.', array['anschlusskleber','kartusche','folie'], 'Luftdichte Anschluesse an Bauteile', null, 76),
    ('folien', 'unterdeckbahnen', 'Traufstreifen diffusionsoffen', 'm', 'Rolle', 40, 'Streifenware fuer Traufbereich.', array['traufstreifen','unterdeckbahn','traufbereich'], 'Saubere Wasserfuehrung an der Traufe', null, 58),

    ('steildach', 'dachziegel', 'Tonziegel Doppelmulde naturrot', 'Stueck', 'Palette', 300, 'Gaengiger Tonziegel fuer Steildaecher.', array['tonziegel','doppelmulde','ziegel'], 'Neueindeckung und Reparatur', null, 88),
    ('steildach', 'dachziegel', 'Tonziegel Hohlfalzziegel naturrot', 'Stueck', 'Palette', 300, 'Klassischer Falzziegel.', array['hohlfalzziegel','tonziegel','ziegel'], 'Steildachdeckung im Bestand', null, 84),
    ('steildach', 'dachziegel', 'Tonziegel Flachdachziegel engobiert', 'Stueck', 'Palette', 250, 'Flach wirkender Tonziegel.', array['flachdachziegel','tonziegel','engobe'], 'Steildach mit flacher Optik', null, 78),
    ('steildach', 'dachziegel', 'Tonziegel Biberschwanz naturrot', 'Stueck', 'Palette', 500, 'Biberschwanz fuer traditionelle Deckungen.', array['biberschwanz','tonziegel','biber'], 'Doppeldeckung und Kronendeckung', null, 76),
    ('steildach', 'dachziegel', 'Betondachstein Frankfurter Pfanne', 'Stueck', 'Palette', 300, 'Gaengiger Betondachstein.', array['betondachstein','frankfurter pfanne','dachstein'], 'Standarddeckung und Reparatur', null, 86),
    ('steildach', 'dachziegel', 'Betondachstein Doppel-S', 'Stueck', 'Palette', 300, 'Betondachstein fuer wirtschaftliche Deckung.', array['doppel s','betondachstein','dachstein'], 'Steildachdeckung', null, 78),
    ('steildach', 'dachziegel', 'Ortgangziegel links passend', 'Stueck', 'Palette', 20, 'Formziegel fuer linken Ortgang.', array['ortgangziegel','links','formziegel'], 'Ortgangabschluss', null, 70),
    ('steildach', 'dachziegel', 'Ortgangziegel rechts passend', 'Stueck', 'Palette', 20, 'Formziegel fuer rechten Ortgang.', array['ortgangziegel','rechts','formziegel'], 'Ortgangabschluss', null, 70),
    ('steildach', 'first-grat', 'Firstziegel passend naturrot', 'Stueck', 'Palette', 50, 'Firstziegel fuer Steildach.', array['firstziegel','first','grat'], 'First- und Gratdeckung', null, 86),
    ('steildach', 'first-grat', 'Gratanfaenger passend', 'Stueck', 'Karton', 8, 'Formteil fuer Gratbeginn.', array['gratanfaenger','grat','formteil'], 'Gratabschluss', null, 48),
    ('steildach', 'first-grat', 'Firstendscheibe passend', 'Stueck', 'Karton', 8, 'Endscheibe fuer Firstabschluss.', array['firstendscheibe','firstabschluss','formteil'], 'Firstabschluss', null, 52),
    ('steildach', 'first-grat', 'Firstrolle Aluminium 300 mm', 'm', 'Rolle', 40, 'Belueftete First- und Gratrolle.', array['firstrolle','gratrolle','alu'], 'Trockener First und Grat', null, 96),
    ('steildach', 'first-grat', 'Firstklammer Edelstahl', 'Stueck', 'Karton', 100, 'Klammer fuer Firstziegel.', array['firstklammer','first','edelstahl'], 'Befestigung von Firstziegeln', null, 82),
    ('steildach', 'zubehoer', 'Trauflueftungskamm mit Gitter', 'm', 'Karton', 60, 'Lueftung und Vogelschutz an der Traufe.', array['trauflueftung','lueftungskamm','vogelschutz'], 'Traufdetail im Steildach', null, 92),
    ('steildach', 'zubehoer', 'Traufelement mit Lueftung 1 m', 'Stueck', 'Karton', 20, 'Fertiges Traufelement fuer Ziegeldaecher.', array['traufelement','trauflueftung','trauf'], 'Traufausbildung', null, 74),
    ('steildach', 'zubehoer', 'Schneefanggitter 3 m verzinkt', 'Stueck', 'Bund', 8, 'Schneefang fuer Steildaecher.', array['schneefang','schneefanggitter','gitter'], 'Schneesicherung', null, 66),
    ('steildach', 'zubehoer', 'Schneefanghaken passend', 'Stueck', 'Karton', 80, 'Haken fuer Schneefanggitter.', array['schneefanghaken','schneefang','haken'], 'Befestigung Schneefang', null, 64),
    ('steildach', 'zubehoer', 'Laufrost 800 mm verzinkt', 'Stueck', 'Karton', 6, 'Dachtritt fuer Wartungswege.', array['laufrost','dachtritt','wartung'], 'Wartungsweg am Dach', null, 58),
    ('steildach', 'zubehoer', 'Laufroststuetze passend', 'Stueck', 'Karton', 12, 'Stuetzung fuer Laufrost.', array['laufroststuetze','dachtritt','stuetze'], 'Montage Laufrost', null, 56),
    ('steildach', 'zubehoer', 'Dunstrohrdurchgang DN 100 passend', 'Stueck', 'Karton', 6, 'Durchgangspfanne fuer Entlueftung.', array['dunstrohr','durchgang','dn100'], 'Sanitaerentlueftung durch Dachdeckung', null, 62),
    ('steildach', 'zubehoer', 'Antennendurchgang passend', 'Stueck', 'Karton', 4, 'Formteil fuer Mastdurchfuehrung.', array['antennendurchgang','mast','durchgang'], 'Antennen- und Mastdurchfuehrung', null, 40),
    ('steildach', 'zubehoer', 'Ersatzpfanne universal Kunststoff', 'Stueck', 'Karton', 10, 'Universelle Reparaturpfanne.', array['ersatzpfanne','reparatur','universal'], 'Schnelle Reparatur im Ziegeldach', null, 54),

    ('flachdach', 'bitumenbahnen', 'Bitumenbahn V60 S4 talkumiert', 'm2', 'Rolle', 60, 'Unterlagsbahn fuer mehrlagige Abdichtung.', array['v60 s4','bitumenbahn','unterlagsbahn'], 'Flachdach und Bauwerksabdichtung', null, 94),
    ('flachdach', 'bitumenbahnen', 'Bitumenbahn G200 S4 talkumiert', 'm2', 'Rolle', 50, 'Glasgewebe-Unterlagsbahn.', array['g200 s4','bitumenbahn','glasgewebe'], 'Unterlage und Sanierung', null, 88),
    ('flachdach', 'bitumenbahnen', 'Polymerbitumenbahn PYE PV200 S5 beschiefert', 'm2', 'Rolle', 60, 'Oberlagsbahn fuer Flachdachabdichtung.', array['pye pv200 s5','oberlagsbahn','bitumen'], 'Oberlage auf Flachdach', null, 98),
    ('flachdach', 'bitumenbahnen', 'Polymerbitumenbahn PYE G200 S4 talkumiert', 'm2', 'Rolle', 40, 'Elastomerbitumen-Unterlagsbahn.', array['pye g200 s4','bitumen','unterlage'], 'Unterlage bei mehrlagiger Abdichtung', null, 84),
    ('flachdach', 'bitumenbahnen', 'Kaltselbstklebebahn KSK DUO', 'm2', 'Rolle', 40, 'Selbstklebende Bitumenbahn.', array['ksk','kaltselbstklebebahn','selbstklebend'], 'Detail- und Sanierungsabdichtung', null, 78),
    ('flachdach', 'bitumenbahnen', 'Dampfsperrbahn AL G200 S4', 'm2', 'Rolle', 40, 'Bituminoese Dampfsperre mit Alueinlage.', array['dampfsperrbahn','al g200','bitumen'], 'Dampfsperre auf Trapezblech oder Beton', null, 76),
    ('flachdach', 'kunststoffbahnen', 'PVC Dachbahn 1,5 mm hellgrau', 'm2', 'Rolle', 80, 'Kunststoff-Dachbahn fuer Flachdach.', array['pvc dachbahn','kunststoffbahn','flachdach'], 'Einlagige Flachdachabdichtung', null, 62),
    ('flachdach', 'kunststoffbahnen', 'FPO Dachbahn 1,5 mm hellgrau', 'm2', 'Rolle', 80, 'FPO-Bahn fuer Flachdachabdichtung.', array['fpo','tpo','dachbahn'], 'Einlagige Abdichtung', null, 60),
    ('flachdach', 'schutzlagen', 'Polyestervlies 300 g', 'm2', 'Rolle', 100, 'Schutz- und Trennlage.', array['polyestervlies','schutzlage','trennlage'], 'Unterlage unter Dachbahnen und Kies', null, 82),
    ('flachdach', 'schutzlagen', 'Bautenschutzmatte 6 mm', 'm2', 'Rolle', 50, 'Gummigranulatmatte als Schutzlage.', array['bautenschutzmatte','schutzmatte','granulat'], 'Schutz unter Plattenlagern und Wegen', null, 70),
    ('flachdach', 'schutzlagen', 'Wurzelschutzbahn PE', 'm2', 'Rolle', 50, 'Schutzlage fuer Gruendachaufbauten.', array['wurzelschutz','gruendach','pe'], 'Gruendach und Schutzabdichtung', null, 54),
    ('flachdach', 'ablaeufe', 'Dachablauf senkrecht DN 100', 'Stueck', 'Karton', 4, 'Ablauf fuer Flachdachentwaesserung.', array['dachablauf','dn100','senkrecht'], 'Innenentwaesserung Flachdach', null, 78),
    ('flachdach', 'ablaeufe', 'Dachablauf waagerecht DN 100', 'Stueck', 'Karton', 4, 'Seitlicher Dachablauf.', array['dachablauf','dn100','waagerecht'], 'Attika- und Flachdachentwaesserung', null, 72),
    ('flachdach', 'ablaeufe', 'Notueberlauf Rechteck Edelstahl', 'Stueck', 'Karton', 3, 'Notentwaesserung an der Attika.', array['notueberlauf','speier','attika'], 'Notentwaesserung Flachdach', null, 68),
    ('flachdach', 'ablaeufe', 'Laubfangkorb fuer Dachablauf', 'Stueck', 'Karton', 8, 'Schutzkorb fuer Dachablauf.', array['laubfangkorb','dachablauf','korb'], 'Verhindert Verstopfung am Ablauf', null, 74),
    ('flachdach', 'zubehoer', 'Kiesfangleiste Aluminium 100 mm', 'm', 'Bund', 30, 'Leiste fuer Kiesrand und Begruenung.', array['kiesfangleiste','alu','flachdach'], 'Abschluss von Kies- und Gruendachflaechen', null, 58),
    ('flachdach', 'zubehoer', 'Attikaablauf DN 70', 'Stueck', 'Karton', 4, 'Ablauf durch Attika.', array['attikaablauf','dn70','speier'], 'Attikaentwaesserung', null, 56),
    ('flachdach', 'zubehoer', 'Dachdurchfuehrung Flachdach universal', 'Stueck', 'Karton', 4, 'Universal-Durchfuehrung fuer Leitungen.', array['dachdurchfuehrung','flachdach','universal'], 'Kabel und Rohre durch Flachdach', null, 50),
    ('flachdach', 'zubehoer', 'Druckausgleichsluefter Bitumen', 'Stueck', 'Karton', 6, 'Luefter fuer Sanierungsdaecher.', array['druckausgleichsluefter','sanierung','bitumen'], 'Feuchteausgleich bei Sanierung', null, 52),
    ('flachdach', 'schutzlagen', 'Draenagematte 20 mm', 'm2', 'Rolle', 40, 'Draen- und Schutzmatte.', array['draenagematte','drainage','gruendach'], 'Gruendach und Terrassendach', null, 48),

    ('spenglerei', 'dachrinne', 'Dachrinne halbrund RG 333 Zink', 'm', 'Bund', 30, 'Gaengige Zink-Dachrinne.', array['dachrinne','rg333','zink'], 'Dachentwaesserung Einfamilienhaus', null, 94),
    ('spenglerei', 'dachrinne', 'Dachrinne halbrund RG 280 Zink', 'm', 'Bund', 30, 'Kleinere Zink-Dachrinne.', array['dachrinne','rg280','zink'], 'Gauben und kleinere Dachflaechen', null, 80),
    ('spenglerei', 'dachrinne', 'Rinnenboden RG 333 links Zink', 'Stueck', 'Karton', 8, 'Endboden fuer Dachrinne.', array['rinnenboden','rg333','links'], 'Rinnenabschluss', null, 72),
    ('spenglerei', 'dachrinne', 'Rinnenboden RG 333 rechts Zink', 'Stueck', 'Karton', 8, 'Endboden fuer Dachrinne.', array['rinnenboden','rg333','rechts'], 'Rinnenabschluss', null, 72),
    ('spenglerei', 'dachrinne', 'Rinnenwinkel RG 333 90 Grad Zink', 'Stueck', 'Karton', 6, 'Winkel fuer Dachrinne.', array['rinnenwinkel','rg333','winkel'], 'Rinnenumlenkung', null, 66),
    ('spenglerei', 'dachrinne', 'Rinnenverbinder RG 333 Zink', 'Stueck', 'Karton', 12, 'Verbinder fuer Rinnenstoss.', array['rinnenverbinder','rg333','verbinder'], 'Rinnenverbindung', null, 78),
    ('spenglerei', 'dachrinne', 'Rinnenhalter RG 333 verzinkt lang', 'Stueck', 'Bund', 30, 'Rinneneisen fuer Traufbohle.', array['rinnenhalter','rinneneisen','rg333'], 'Befestigung Dachrinne', null, 90),
    ('spenglerei', 'dachrinne', 'Rinnenhalter RG 333 justierbar', 'Stueck', 'Bund', 20, 'Verstellbarer Rinnenhalter.', array['rinnenhalter','justierbar','rg333'], 'Sanierung und Ausgleich', null, 70),
    ('spenglerei', 'fallrohr', 'Fallrohr DN 100 Zink', 'm', 'Bund', 24, 'Standard-Fallrohr aus Zink.', array['fallrohr','dn100','zink'], 'Dachentwaesserung', null, 88),
    ('spenglerei', 'fallrohr', 'Fallrohrbogen DN 100 72 Grad Zink', 'Stueck', 'Karton', 12, 'Bogen fuer Fallrohrversprung.', array['fallrohrbogen','dn100','bogen'], 'Fallrohranschluss', null, 76),
    ('spenglerei', 'fallrohr', 'Rohrschelle DN 100 Zink mit Schlagstift', 'Stueck', 'Karton', 20, 'Schelle fuer Fallrohrmontage.', array['rohrschelle','dn100','fallrohr'], 'Befestigung Fallrohr', null, 80),
    ('spenglerei', 'fallrohr', 'Standrohr DN 100 verzinkt', 'Stueck', 'Bund', 4, 'Robustes Standrohr im Sockelbereich.', array['standrohr','dn100','fallrohr'], 'Sockelanschluss Fallrohr', null, 52),
    ('spenglerei', 'bleche', 'Traufblech Zink 200 mm', 'm', 'Bund', 30, 'Blech fuer Traufabschluss.', array['traufblech','zink','traufe'], 'Wasserfuehrung an der Traufe', null, 86),
    ('spenglerei', 'bleche', 'Ortgangblech Zink 250 mm', 'm', 'Bund', 24, 'Ortgangabschluss aus Zink.', array['ortgangblech','zink','ortgang'], 'Seitlicher Dachabschluss', null, 78),
    ('spenglerei', 'bleche', 'Kehlblech Zink 500 mm', 'm', 'Bund', 18, 'Kehlrinne fuer geneigte Daecher.', array['kehlblech','kehle','zink'], 'Kehlausbildung', null, 82),
    ('spenglerei', 'bleche', 'Wandanschlussblech Zink 300 mm', 'm', 'Bund', 24, 'Blech fuer Wandanschluss.', array['wandanschluss','anschlussblech','zink'], 'Anschluss an aufgehende Bauteile', null, 84),
    ('spenglerei', 'bleche', 'Mauerabdeckblech Zink 400 mm', 'm', 'Bund', 20, 'Abdeckung fuer Mauerkrone.', array['mauerabdeckung','abdeckblech','zink'], 'Mauer- und Attikaabdeckung', null, 68),
    ('spenglerei', 'bleche', 'Attikaabdeckung Aluminium 500 mm', 'm', 'Bund', 20, 'Aluminium-Abdeckung fuer Attika.', array['attikaabdeckung','alu','attika'], 'Flachdachrand und Attika', null, 60),
    ('spenglerei', 'bleche', 'Aluminium Rolle glatt 0,7 mm anthrazit', 'm2', 'Rolle', 20, 'Beschichtetes Alu fuer Kantteile.', array['aluminium','rolle','anthrazit'], 'Kantteile und Anschluesse', null, 50),
    ('spenglerei', 'bleche', 'Zinkblech Tafel 0,7 mm', 'm2', 'Tafel', 20, 'Tafelware fuer Spenglerdetails.', array['zinkblech','tafel','spenglerei'], 'Kantteile, Reparatur und Abdeckung', null, 72),
    ('spenglerei', 'bleche', 'Kupferblech Tafel 0,6 mm', 'm2', 'Tafel', 8, 'Kupfer-Tafelware fuer Anschluesse.', array['kupferblech','kupfer','tafel'], 'Hochwertige Anschluesse und Denkmal', null, 42),
    ('spenglerei', 'anschluesse', 'Kaminanschlussband Aluminium Butyl 300 mm', 'm', 'Rolle', 20, 'Anschlussband fuer Kamin und Wand.', array['kaminanschlussband','wakaflex','butyl'], 'Kamin- und Wandanschluss', null, 82),
    ('spenglerei', 'anschluesse', 'Kaminabdeckhaube Edelstahl universal', 'Stueck', 'Karton', 2, 'Haube fuer Kaminabdeckung.', array['kaminhaube','abdeckhaube','edelstahl'], 'Kaminabschluss', null, 36),
    ('spenglerei', 'anschluesse', 'Wandanschlussprofil Aluminium', 'm', 'Bund', 20, 'Profil fuer Anschlussabdichtung.', array['wandanschlussprofil','alu','profil'], 'Anschluss mit Dichtstofffuge', null, 64),
    ('spenglerei', 'anschluesse', 'Kappleiste Aluminium gelocht', 'm', 'Bund', 20, 'Kappleiste fuer Wandanschluesse.', array['kappleiste','alu','anschluss'], 'Mechanische Sicherung von Anschluessen', null, 62),

    ('befestigung', 'schrauben', 'Spenglerschraube 4,5 x 35 mm Edelstahl mit Dichtscheibe', 'Stueck', 'Karton', 300, 'Schraube fuer Bleche und Profile.', array['spenglerschraube','dichtscheibe','edelstahl'], 'Blechbefestigung im Aussenbereich', null, 98),
    ('befestigung', 'schrauben', 'Spenglerschraube 4,5 x 45 mm Edelstahl mit Dichtscheibe', 'Stueck', 'Karton', 250, 'Laengere Spenglerschraube.', array['spenglerschraube','4,5x45','dichtscheibe'], 'Blech- und Profilbefestigung', null, 90),
    ('befestigung', 'schrauben', 'Holzbauschraube 6 x 120 mm Tellerkopf', 'Stueck', 'Karton', 100, 'Tellerkopfschraube fuer Holzverbindungen.', array['holzbauschraube','tellerkopf','6x120'], 'Konterlatten und Holzbauanschluesse', null, 84),
    ('befestigung', 'schrauben', 'Holzbauschraube 8 x 160 mm Tellerkopf', 'Stueck', 'Karton', 80, 'Staerkere Holzbauschraube.', array['holzbauschraube','8x160','tellerkopf'], 'Aufsparrendaemmung und Holzbau', null, 76),
    ('befestigung', 'schrauben', 'Terrassenschraube Edelstahl 5 x 60 mm', 'Stueck', 'Karton', 100, 'Edelstahlschraube fuer Aussenholz.', array['terrassenschraube','edelstahl','5x60'], 'Holzdetails und Aussenbereich', null, 52),
    ('befestigung', 'schrauben', 'Bohrschraube 4,8 x 35 mm verzinkt', 'Stueck', 'Karton', 250, 'Bohrschraube fuer Metallprofile.', array['bohrschraube','metall','4,8x35'], 'Blech- und Profilmontage', null, 70),
    ('befestigung', 'schrauben', 'Dachbauschraube 6,5 x 130 mm mit Dichtscheibe', 'Stueck', 'Karton', 100, 'Schraube fuer Dachaufbauten.', array['dachbauschraube','dichtscheibe','6,5x130'], 'Befestigung von Platten und Profilen', null, 62),
    ('befestigung', 'naegel', 'Dachpappstift 2,8 x 25 mm verzinkt', 'kg', 'Karton', 10, 'Breitkopfnagel fuer Bahnen.', array['dachpappstift','pappnagel','breitkopf'], 'Befestigung von Dachpappe und Folien', null, 88),
    ('befestigung', 'naegel', 'Dachpappstift 3,1 x 30 mm verzinkt', 'kg', 'Karton', 10, 'Breitkopfnagel fuer staerkere Lagen.', array['dachpappstift','3,1x30','pappnagel'], 'Mechanische Befestigung', null, 80),
    ('befestigung', 'naegel', 'Schiefernagel Edelstahl 2,8 x 35 mm', 'kg', 'Karton', 5, 'Nagel fuer Schieferdeckung.', array['schiefernagel','edelstahl','schiefer'], 'Schiefer- und Faserzementdeckung', null, 60),
    ('befestigung', 'naegel', 'Haftenagel verzinkt 2,5 x 25 mm', 'kg', 'Karton', 5, 'Nagel fuer Haften und Bleche.', array['haftenagel','zink','blech'], 'Blechbefestigung mit Haften', null, 58),
    ('befestigung', 'klammern', 'Sturmklammer Typ passend Edelstahl', 'Stueck', 'Karton', 300, 'Klammer gegen Windsog.', array['sturmklammer','windsog','dachziegel'], 'Sicherung von Dachziegeln', null, 100),
    ('befestigung', 'klammern', 'Seitenfalzklammer Edelstahl', 'Stueck', 'Karton', 200, 'Klammer fuer Seitenfalz.', array['seitenfalzklammer','klammer','edelstahl'], 'Ziegelsicherung', null, 82),
    ('befestigung', 'klammern', 'Biberschwanzklammer Edelstahl', 'Stueck', 'Karton', 200, 'Klammer fuer Biberschwanzdeckung.', array['biberschwanzklammer','biber','klammer'], 'Befestigung Biberschwanz', null, 66),
    ('befestigung', 'klammern', 'Schieferhaken Edelstahl 80 mm', 'Stueck', 'Karton', 250, 'Haken fuer Schieferdeckung.', array['schieferhaken','schiefer','haken'], 'Schieferreparatur und Deckung', null, 58),
    ('befestigung', 'duebel', 'Rahmenduebel 10 x 120 mm', 'Stueck', 'Karton', 80, 'Duebel fuer Befestigung am Mauerwerk.', array['rahmenduebel','duebel','10x120'], 'Wandanschlussprofile und Konsolen', null, 70),
    ('befestigung', 'duebel', 'Nagelduebel 6 x 40 mm', 'Stueck', 'Karton', 200, 'Schnellduebel fuer leichte Befestigungen.', array['nagelduebel','duebel','6x40'], 'Kappleisten und leichte Profile', null, 72),
    ('befestigung', 'duebel', 'Betonschraube 7,5 x 72 mm', 'Stueck', 'Karton', 80, 'Schraubanker fuer Beton.', array['betonschraube','schraubanker','beton'], 'Befestigung auf Beton und Attika', null, 56),
    ('befestigung', 'schrauben', 'Stockschraube M10 x 200 Edelstahl', 'Stueck', 'Karton', 40, 'Stockschraube fuer Aufstaenderung.', array['stockschraube','m10','solar'], 'Dachdurchdringungen und Halterungen', null, 50),
    ('befestigung', 'schrauben', 'Dichtscheibe EPDM 16 mm', 'Stueck', 'Karton', 300, 'Ersatz-Dichtscheibe fuer Schrauben.', array['dichtscheibe','epdm','scheibe'], 'Abdichtung von Schraubpunkten', null, 64),
    ('befestigung', 'schrauben', 'Unterlegscheibe Edelstahl M8', 'Stueck', 'Karton', 200, 'Scheibe fuer Edelstahlverschraubung.', array['unterlegscheibe','m8','edelstahl'], 'Allgemeine Montage', null, 42),
    ('befestigung', 'schrauben', 'Sechskantmutter Edelstahl M8', 'Stueck', 'Karton', 150, 'Mutter fuer Edelstahlverbindungen.', array['mutter','m8','edelstahl'], 'Allgemeine Montage', null, 40),
    ('befestigung', 'schrauben', 'Blindniete Aluminium 4,8 x 12 mm', 'Stueck', 'Karton', 300, 'Niete fuer Blechverbindungen.', array['blindniete','niete','aluminium'], 'Blech- und Profilverbindungen', null, 66),
    ('befestigung', 'schrauben', 'Haften Edelstahl 25 mm', 'Stueck', 'Karton', 100, 'Haften fuer Stehfalz und Bleche.', array['haften','stehfalz','edelstahl'], 'Blechdeckung und Abdeckungen', null, 54),
    ('befestigung', 'klammern', 'Rinneneinhang Klammer universal', 'Stueck', 'Karton', 80, 'Klammer fuer Rinneneinhang.', array['rinneneinhang','klammer','rinne'], 'Trauf- und Rinnendetails', null, 48),

    ('daemmung', 'mineralwolle', 'Klemmfilz WLG 035 160 mm', 'm2', 'Paket', 40, 'Zwischensparrendaemmung aus Mineralwolle.', array['klemmfilz','mineralwolle','160mm'], 'Zwischensparrendaemmung', null, 76),
    ('daemmung', 'mineralwolle', 'Klemmfilz WLG 035 200 mm', 'm2', 'Paket', 30, 'Dicker Klemmfilz fuer Dachausbau.', array['klemmfilz','200mm','dachausbau'], 'Zwischensparrendaemmung', null, 70),
    ('daemmung', 'mineralwolle', 'Untersparrendaemmung 40 mm', 'm2', 'Paket', 30, 'Zusatzdaemmung unter Sparren.', array['untersparrendaemmung','mineralwolle','40mm'], 'Waermebruecken reduzieren', null, 52),
    ('daemmung', 'pir-pur', 'PIR Aufsparrendaemmung 120 mm Nut und Feder', 'm2', 'Paket', 30, 'Aufsparrendaemmplatte mit hoher Daemmleistung.', array['pir','aufsparrendaemmung','120mm'], 'Energetische Dachsanierung', null, 68),
    ('daemmung', 'pir-pur', 'PIR Aufsparrendaemmung 160 mm Nut und Feder', 'm2', 'Paket', 20, 'Staerkere Aufsparrendaemmung.', array['pir','aufsparrendaemmung','160mm'], 'Dachsanierung nach GEG', null, 62),
    ('daemmung', 'pir-pur', 'Gefalledaemmung PIR 2 Prozent', 'm2', 'Paket', 20, 'PIR-Gefaelleplatten fuer Flachdach.', array['gefaelledaemmung','pir','flachdach'], 'Gefaelleausbildung Flachdach', null, 56),
    ('daemmung', 'xps-eps', 'XPS Platte 60 mm druckfest', 'm2', 'Paket', 30, 'Druckfeste Daemmplatte.', array['xps','daemmplatte','60mm'], 'Umkehrdach und Sockelbereiche', null, 52),
    ('daemmung', 'xps-eps', 'XPS Platte 100 mm druckfest', 'm2', 'Paket', 20, 'Staerkere XPS-Daemmung.', array['xps','100mm','druckfest'], 'Umkehrdach und Attika', null, 48),
    ('daemmung', 'xps-eps', 'EPS Flachdachdaemmung 100 mm', 'm2', 'Paket', 30, 'EPS-Daemmplatte fuer Flachdach.', array['eps','flachdachdaemmung','100mm'], 'Flachdachaufbau', null, 50),
    ('daemmung', 'mineralwolle', 'Brandschutzplatte Mineralwolle 30 mm', 'm2', 'Paket', 20, 'Nichtbrennbare Platte fuer Details.', array['brandschutzplatte','mineralwolle','a1'], 'Brandschutzdetails im Dachbereich', null, 44),
    ('daemmung', 'pir-pur', 'Daemmstoffteller 70 mm Kunststoff', 'Stueck', 'Karton', 200, 'Teller fuer mechanische Daemmbefestigung.', array['daemmstoffteller','teller','daemmung'], 'Befestigung von Daemmplatten', null, 58),
    ('daemmung', 'pir-pur', 'Teleskopbefestiger Flachdach 160 mm', 'Stueck', 'Karton', 100, 'Befestiger fuer Daemmung und Dachbahn.', array['teleskopbefestiger','flachdach','daemmung'], 'Mechanische Befestigung Flachdach', null, 54),

    ('chemie', 'dichtstoffe', 'PU Dichtstoff grau Kartusche', 'Stueck', 'Karton', 12, 'Elastischer Dichtstoff fuer Aussenanschluesse.', array['pu dichtstoff','kartusche','grau'], 'Anschlussfugen und Reparatur', null, 96),
    ('chemie', 'dichtstoffe', 'MS Polymer Dichtstoff schwarz Kartusche', 'Stueck', 'Karton', 12, 'UV-bestaendiger Dichtstoff.', array['ms polymer','dichtstoff','schwarz'], 'Blech- und Dachanschluesse', null, 88),
    ('chemie', 'dichtstoffe', 'Silikon neutralvernetzend transparent', 'Stueck', 'Karton', 12, 'Neutralvernetzendes Silikon.', array['silikon','transparent','neutral'], 'Anschlussfugen ohne Bitumenkontakt', null, 62),
    ('chemie', 'dichtstoffe', 'Acryl Dichtstoff weiss', 'Stueck', 'Karton', 12, 'Acryl fuer Innenfugen.', array['acryl','weiss','fuge'], 'Innenausbau und Anschlussfugen', null, 42),
    ('chemie', 'kleber', 'Bitumenkaltkleber 5 kg', 'Eimer', 'Eimer', 4, 'Kaltkleber fuer Bitumenbahnen.', array['bitumenkaltkleber','kaltkleber','bitumen'], 'Kleben von Bitumenbahnen und Details', null, 72),
    ('chemie', 'primer', 'Bitumenvoranstrich 10 Liter', 'Eimer', 'Eimer', 4, 'Voranstrich fuer bituminoese Abdichtung.', array['bitumenvoranstrich','primer','bitumen'], 'Untergrundvorbereitung', null, 92),
    ('chemie', 'primer', 'Haftgrund fuer Fluessigkunststoff 1 Liter', 'Liter', 'Dose', 6, 'Primer fuer Detailabdichtung.', array['haftgrund','primer','fluessigkunststoff'], 'Vorbereitung fuer Fluessigkunststoff', null, 64),
    ('chemie', 'fluessigkunststoff', 'Fluessigkunststoff Abdichtung grau 5 kg', 'Eimer', 'Eimer', 4, 'Detailabdichtung mit Vliesarmierung.', array['fluessigkunststoff','detailabdichtung','grau'], 'Anschluesse, Lichtkuppeln und Durchdringungen', null, 86),
    ('chemie', 'fluessigkunststoff', 'Armierungsvlies 15 cm', 'm', 'Rolle', 30, 'Vlies fuer Fluessigkunststoff.', array['armierungsvlies','vlies','fluessigkunststoff'], 'Detailabdichtung', null, 78),
    ('chemie', 'fluessigkunststoff', 'Armierungsvlies 30 cm', 'm', 'Rolle', 20, 'Breiteres Vlies fuer Anschluesse.', array['armierungsvlies','30cm','vlies'], 'Detailabdichtung und Anschluesse', null, 66),
    ('chemie', 'kleber', 'Montagekleber Kartusche', 'Stueck', 'Karton', 12, 'Universeller Kleber fuer Montagearbeiten.', array['montagekleber','kartusche','kleber'], 'Leisten, Profile und Nebenarbeiten', null, 68),
    ('chemie', 'kleber', 'PU Schaum B2 Pistole 750 ml', 'Stueck', 'Karton', 12, 'Pistolenschaum fuer Montagefugen.', array['pu schaum','pistolenschaum','b2'], 'Dachfensteranschluss und Montage', null, 70),
    ('chemie', 'primer', 'Reiniger fuer PVC Dachbahn', 'Liter', 'Dose', 4, 'Reiniger fuer Kunststoffbahnen.', array['pvc reiniger','dachbahn','reiniger'], 'Vorbereitung von Schweissnaehten', null, 44),
    ('chemie', 'kleber', 'Kontaktkleber fuer Dachbahn 5 Liter', 'Eimer', 'Eimer', 3, 'Kleber fuer Kunststoffbahnen.', array['kontaktkleber','dachbahn','kleber'], 'Rand- und Anschlussverklebung', null, 40),
    ('chemie', 'dichtstoffe', 'Quellband BG1 15 mm', 'm', 'Rolle', 20, 'Vorkomprimiertes Dichtband.', array['quellband','bg1','dichtband'], 'Anschlussfugen und Abdichtung', null, 48),

    ('dachfenster', 'fenster', 'Dachfenster Kunststoff 78 x 118 cm', 'Stueck', 'Einzel', 1, 'Gaengige Fenstergroesse fuer Dachausbau.', array['dachfenster','kunststoff','78x118'], 'Dachfenstereinbau', null, 42),
    ('dachfenster', 'fenster', 'Dachfenster Holz 78 x 118 cm', 'Stueck', 'Einzel', 1, 'Holzfenster fuer Wohnraeume.', array['dachfenster','holz','78x118'], 'Dachfenstereinbau', null, 36),
    ('dachfenster', 'fenster', 'Ausstiegsfenster 45 x 55 cm', 'Stueck', 'Einzel', 1, 'Einfaches Ausstiegsfenster.', array['ausstiegsfenster','dachausstieg','45x55'], 'Dachausstieg fuer unbeheizte Raeume', null, 44),
    ('dachfenster', 'eindeckrahmen', 'Eindeckrahmen Ziegel 78 x 118 cm', 'Stueck', 'Karton', 2, 'Rahmen fuer profilierte Deckung.', array['eindeckrahmen','ziegel','78x118'], 'Dachfensteranschluss bei Ziegeldeckung', null, 50),
    ('dachfenster', 'eindeckrahmen', 'Eindeckrahmen Schiefer 78 x 118 cm', 'Stueck', 'Karton', 1, 'Rahmen fuer flache Deckung.', array['eindeckrahmen','schiefer','flach'], 'Dachfensteranschluss bei Schiefer', null, 30),
    ('dachfenster', 'anschlussprodukte', 'Dampfsperrschuerze Dachfenster', 'Stueck', 'Karton', 3, 'Innenanschluss fuer Luftdichtheit.', array['dampfsperrschuerze','dachfenster','luftdicht'], 'Innenanschluss Dachfenster', null, 42),
    ('dachfenster', 'anschlussprodukte', 'Unterdachschuerze Dachfenster', 'Stueck', 'Karton', 3, 'Aussenanschluss an Unterdeckbahn.', array['unterdachschuerze','dachfenster','unterdeckbahn'], 'Regensicherer Aussenanschluss', null, 44),
    ('dachfenster', 'anschlussprodukte', 'Daemmrahmen Dachfenster 78 x 118 cm', 'Stueck', 'Karton', 2, 'Waermegedaemmter Anschlussrahmen.', array['daemmrahmen','dachfenster','78x118'], 'Waermebrueckenarmer Einbau', null, 34),
    ('dachfenster', 'anschlussprodukte', 'Innenfutter Grundelement 78 x 118 cm', 'Stueck', 'Karton', 1, 'Innenfutter fuer Dachfenster.', array['innenfutter','dachfenster','78x118'], 'Innenausbau Dachfenster', null, 24),
    ('dachfenster', 'anschlussprodukte', 'Rollladen Anschlusskabel Dachfenster', 'Stueck', 'Karton', 2, 'Zubehoer fuer elektrischen Rollladen.', array['rollladen','anschlusskabel','dachfenster'], 'Dachfensterzubehoer', null, 18),

    ('sicherheit', 'psa', 'Schutzhandschuhe Montage Gr. 10', 'Paar', 'Karton', 30, 'Allround-Handschuhe fuer Baustelle.', array['handschuhe','montagehandschuhe','psa'], 'Taeglicher Handschutz', null, 100),
    ('sicherheit', 'psa', 'Schnittschutzhandschuhe Klasse B', 'Paar', 'Karton', 12, 'Handschuhe fuer Blech- und Schneidarbeiten.', array['schnittschutz','handschuhe','blech'], 'Arbeiten mit Blech und Messer', null, 86),
    ('sicherheit', 'psa', 'Schutzbrille klar', 'Stueck', 'Karton', 12, 'Augenschutz fuer Schleifen und Bohren.', array['schutzbrille','brille','psa'], 'Augenschutz', null, 82),
    ('sicherheit', 'psa', 'Gehoerschutzstoepsel', 'Paar', 'Karton', 100, 'Einweg-Gehoerschutz.', array['gehoerschutz','stoepsel','laerm'], 'Laute Maschinenarbeiten', null, 72),
    ('sicherheit', 'psa', 'FFP2 Staubmaske', 'Stueck', 'Karton', 50, 'Maske gegen Staub.', array['ffp2','staubmaske','maske'], 'Rueckbau und Schneidarbeiten', null, 78),
    ('sicherheit', 'psa', 'Schutzhelm mit Kinnriemen', 'Stueck', 'Einzel', 4, 'Helm fuer Arbeiten auf dem Dach.', array['schutzhelm','helm','kinnriemen'], 'Kopfschutz und PSA', null, 64),
    ('sicherheit', 'absturzsicherung', 'Auffanggurt Groesse M-XL', 'Stueck', 'Einzel', 3, 'Persoenlicher Auffanggurt.', array['auffanggurt','absturzsicherung','gurt'], 'Arbeiten mit Absturzgefahr', null, 58),
    ('sicherheit', 'absturzsicherung', 'Verbindungsmittel mit Falldaempfer 2 m', 'Stueck', 'Einzel', 3, 'Verbindungsmittel fuer PSA gegen Absturz.', array['verbindungsmittel','falldaempfer','psaga'], 'Sicherung am Anschlagpunkt', null, 54),
    ('sicherheit', 'absturzsicherung', 'Bandschlinge 1 m', 'Stueck', 'Einzel', 6, 'Anschlagmittel fuer Sicherung.', array['bandschlinge','anschlagmittel','absturz'], 'Anschlagpunkt und Sicherung', null, 50),
    ('sicherheit', 'absturzsicherung', 'Karabiner Stahl Trilock', 'Stueck', 'Einzel', 8, 'Sicherheitskarabiner.', array['karabiner','trilock','stahl'], 'PSA und Anschlagpunkte', null, 48),
    ('sicherheit', 'absturzsicherung', 'Seitenschutzhalter universal', 'Stueck', 'Einzel', 8, 'Halter fuer temporaeren Seitenschutz.', array['seitenschutz','halter','absturz'], 'Dachrandabsicherung', null, 42),
    ('sicherheit', 'absturzsicherung', 'Absperrband rot weiss', 'm', 'Rolle', 100, 'Band zur Baustellenabsperrung.', array['absperrband','rot weiss','baustelle'], 'Sicherung und Markierung', null, 66),

    ('werkzeug', 'handwerkzeug', 'Cuttermesser robust', 'Stueck', 'Einzel', 8, 'Messer fuer Bahnen und Folien.', array['cuttermesser','messer','cutter'], 'Zuschnitt von Bahnen und Folien', null, 90),
    ('werkzeug', 'verbrauch', 'Cutterklingen 18 mm', 'Stueck', 'Packung', 100, 'Ersatzklingen fuer Cuttermesser.', array['cutterklingen','klingen','18mm'], 'Verbrauchsmaterial fuer Zuschnitt', null, 96),
    ('werkzeug', 'handwerkzeug', 'Lattenhammer mit Magnet', 'Stueck', 'Einzel', 4, 'Hammer fuer Dachdeckerarbeiten.', array['lattenhammer','hammer','dachdecker'], 'Lattung und Dacharbeiten', null, 70),
    ('werkzeug', 'handwerkzeug', 'Schieferhammer rechts', 'Stueck', 'Einzel', 2, 'Hammer fuer Schieferarbeiten.', array['schieferhammer','schiefer','hammer'], 'Schieferdeckung und Reparatur', null, 38),
    ('werkzeug', 'handwerkzeug', 'Falzzange gerade 60 mm', 'Stueck', 'Einzel', 3, 'Zange fuer Blechfalze.', array['falzzange','zange','blech'], 'Spenglerarbeiten', null, 58),
    ('werkzeug', 'handwerkzeug', 'Falzzange gebogen 45 Grad', 'Stueck', 'Einzel', 2, 'Gebogene Zange fuer Detailfalze.', array['falzzange','gebogen','blech'], 'Spenglerdetails', null, 46),
    ('werkzeug', 'handwerkzeug', 'Blechschere rechts', 'Stueck', 'Einzel', 3, 'Schere fuer Blechzuschnitt.', array['blechschere','rechts','schere'], 'Spenglerarbeiten', null, 66),
    ('werkzeug', 'handwerkzeug', 'Blechschere links', 'Stueck', 'Einzel', 3, 'Linksschneidende Blechschere.', array['blechschere','links','schere'], 'Spenglerarbeiten', null, 66),
    ('werkzeug', 'maschinenzubehoer', 'Trennscheibe Metall 125 mm', 'Stueck', 'Packung', 50, 'Scheibe fuer Winkelschleifer.', array['trennscheibe','metall','125mm'], 'Metallzuschnitt', null, 92),
    ('werkzeug', 'maschinenzubehoer', 'Diamanttrennscheibe 125 mm', 'Stueck', 'Packung', 8, 'Scheibe fuer harte Baustoffe.', array['diamanttrennscheibe','125mm','stein'], 'Ziegel, Beton und Stein schneiden', null, 78),
    ('werkzeug', 'maschinenzubehoer', 'Bit TX20 lang', 'Stueck', 'Packung', 20, 'Schrauberbit fuer gaengige Schrauben.', array['bit','tx20','torx'], 'Montagearbeiten', null, 84),
    ('werkzeug', 'maschinenzubehoer', 'Bit TX25 lang', 'Stueck', 'Packung', 20, 'Schrauberbit fuer Holzbauschrauben.', array['bit','tx25','torx'], 'Montagearbeiten', null, 88),
    ('werkzeug', 'maschinenzubehoer', 'Bit TX30 lang', 'Stueck', 'Packung', 20, 'Schrauberbit fuer groessere Schrauben.', array['bit','tx30','torx'], 'Montagearbeiten', null, 76),
    ('werkzeug', 'maschinenzubehoer', 'Metallbohrer HSS 4 mm', 'Stueck', 'Packung', 10, 'Bohrer fuer Metall.', array['metallbohrer','hss','4mm'], 'Bohren in Blech und Metall', null, 50),
    ('werkzeug', 'maschinenzubehoer', 'Metallbohrer HSS 6 mm', 'Stueck', 'Packung', 10, 'Bohrer fuer Metall.', array['metallbohrer','hss','6mm'], 'Bohren in Blech und Metall', null, 52),
    ('werkzeug', 'maschinenzubehoer', 'Steinbohrer SDS 8 mm', 'Stueck', 'Packung', 6, 'Bohrer fuer Mauerwerk.', array['steinbohrer','sds','8mm'], 'Befestigung in Mauerwerk', null, 54),
    ('werkzeug', 'verbrauch', 'Abdeckplane 4 x 6 m', 'Stueck', 'Einzel', 6, 'Plane zum Abdecken offener Flaechen.', array['abdeckplane','plane','4x6'], 'Wetterschutz und Baustellensicherung', null, 90),
    ('werkzeug', 'verbrauch', 'Gewebeplane 6 x 8 m', 'Stueck', 'Einzel', 4, 'Groessere Plane fuer Dachflaechen.', array['gewebeplane','plane','6x8'], 'Notabdichtung und Wetterschutz', null, 82),
    ('werkzeug', 'verbrauch', 'Muellsaecke 120 Liter extra stark', 'Stueck', 'Rolle', 50, 'Stabile Saecke fuer Baustellenabfall.', array['muellsaecke','baustellenabfall','120l'], 'Saubere Baustelle', null, 88),
    ('werkzeug', 'verbrauch', 'Klebeband Panzerband 50 mm', 'm', 'Rolle', 60, 'Universelles Gewebeband.', array['panzerband','gewebeband','klebeband'], 'Provisorische Befestigung und Schutz', null, 94),
    ('werkzeug', 'verbrauch', 'Markierungsspray rot', 'Stueck', 'Karton', 6, 'Spray fuer Markierungen.', array['markierungsspray','rot','spray'], 'Baustellenmarkierung', null, 46),
    ('werkzeug', 'verbrauch', 'Baueimer 20 Liter', 'Stueck', 'Einzel', 10, 'Eimer fuer Material und Reinigung.', array['baueimer','eimer','20l'], 'Alltag auf Baustelle und Hof', null, 72),
    ('werkzeug', 'verbrauch', 'Kehrbesen Baustelle', 'Stueck', 'Einzel', 4, 'Besen fuer grobe Reinigung.', array['kehrbesen','besen','baustelle'], 'Baustellenreinigung', null, 54)
)
insert into public.material_catalog (
  category_id,
  subcategory_id,
  name,
  unit,
  package_unit,
  default_minimum_stock,
  short_description,
  search_terms,
  typical_use,
  manufacturer,
  popularity
)
select
  c.id,
  s.id,
  r.name,
  r.unit,
  r.package_unit,
  r.default_minimum_stock,
  r.short_description,
  r.search_terms,
  r.typical_use,
  r.manufacturer,
  r.popularity
from catalog_rows r
join public.material_categories c on c.slug = r.category_slug
left join public.material_subcategories s on s.category_id = c.id and s.slug = r.subcategory_slug
on conflict (name, unit, package_unit) do update set
  category_id = excluded.category_id,
  subcategory_id = excluded.subcategory_id,
  default_minimum_stock = excluded.default_minimum_stock,
  short_description = excluded.short_description,
  search_terms = excluded.search_terms,
  typical_use = excluded.typical_use,
  manufacturer = excluded.manufacturer,
  popularity = excluded.popularity,
  active = true;

insert into public.material_aliases (catalog_item_id, alias)
select mc.id, aliases.alias_value
from public.material_catalog mc
cross join lateral unnest(mc.search_terms) as aliases(alias_value)
where mc.active = true
on conflict (catalog_item_id, alias) do nothing;

insert into public.material_import_templates (name, description, columns)
values
  ('Startbestand Materiallager', 'Vorlage fuer die erste Lageraufnahme.', array['Materialname','Lagerort','Bestand','Mindestbestand','Einheit','EK-Preis','Lieferant']),
  ('Fahrzeugbestand Dachdecker', 'Vorlage fuer Standardmaterial im Fahrzeug.', array['Materialname','Fahrzeug','Bestand','Mindestbestand','Einheit'])
on conflict (name) do update set
  description = excluded.description,
  columns = excluded.columns,
  active = true;

with rule_rows (
  rule_key,
  roof_type,
  name,
  material_name,
  unit,
  calculation_method,
  factor,
  spacing_m,
  waste_applies,
  sort_order
) as (
  values
    ('steildach_dachziegel', 'steildach', 'Dachziegel aus Flaeche', 'Tonziegel Doppelmulde naturrot', 'Stueck', 'area', 10.5, null, true, 10),
    ('steildach_unterspannbahn', 'steildach', 'Unterspannbahn aus Dachflaeche', 'Unterspannbahn diffusionsoffen 160 g', 'm2', 'area', 1, null, true, 20),
    ('steildach_konterlatten', 'steildach', 'Konterlatten grob aus Dachflaeche', 'Konterlatte 30 x 50 mm imprraegniert', 'm', 'area', 1.6, null, true, 30),
    ('steildach_dachlatten', 'steildach', 'Dachlatten aus Flaeche und Lattenabstand', 'Dachlatte 30 x 50 mm S10 imprraegniert', 'm', 'area_per_spacing', 1, 0.33, true, 40),
    ('steildach_schrauben_naegel', 'steildach', 'Schrauben/Naegel grob aus Flaeche', 'Dachdecker-Schrauben und Naegel gemischt', 'Stueck', 'area', 8, null, true, 45),
    ('steildach_firstrolle', 'steildach', 'Firstrolle aus Firstlaenge', 'Firstrolle Aluminium 300 mm', 'm', 'first_length', 1, null, true, 50),
    ('steildach_sturmklammern', 'steildach', 'Sturmklammern grob pro m2', 'Sturmklammer Typ passend Edelstahl', 'Stueck', 'area', 5, null, true, 60),
    ('steildach_traufblech', 'steildach', 'Traufblech aus Trauflaenge', 'Traufblech Zink 200 mm', 'm', 'eaves_length', 1, null, true, 70),
    ('steildach_ortgangblech', 'steildach', 'Ortgangblech aus Ortganglaenge', 'Ortgangblech Zink 250 mm', 'm', 'verge_length', 1, null, true, 80),
    ('steildach_kehlblech', 'steildach', 'Kehlblech aus Kehllaenge', 'Kehlblech Zink 500 mm', 'm', 'valley_length', 1, null, true, 90),
    ('steildach_gaubenanschluss', 'steildach', 'Gauben-Anschlussmaterial', 'Anschlussband fuer Gauben und Einfassungen', 'Stueck', 'dormers_count', 1, null, true, 100),
    ('steildach_schornsteinanschluss', 'steildach', 'Schornstein-Anschlussmaterial', 'Schornstein-Anschlussset Blei/Flex', 'Stueck', 'chimneys_count', 1, null, true, 110),

    ('flachdach_dampfsperre', 'flachdach', 'Dampfsperre aus Flaeche', 'Dampfsperrbahn AL G200 S4', 'm2', 'area', 1, null, true, 10),
    ('flachdach_daemmung', 'flachdach', 'Daemmung aus Flaeche', 'PIR Aufsparrendaemmung 120 mm Nut und Feder', 'm2', 'area', 1, null, true, 20),
    ('flachdach_unterlage', 'flachdach', 'Schweissbahn Unterlage aus Flaeche', 'Bitumenbahn V60 S4 talkumiert', 'm2', 'area', 1, null, true, 30),
    ('flachdach_oberlage', 'flachdach', 'Schweissbahn Oberlage aus Flaeche', 'Polymerbitumenbahn PYE PV200 S5 beschiefert', 'm2', 'area', 1, null, true, 40),
    ('flachdach_voranstrich', 'flachdach', 'Voranstrich 0,3 l pro m2', 'Bitumenvoranstrich 10 Liter', 'Liter', 'area', 0.3, null, true, 50),
    ('flachdach_fluessigkunststoff', 'flachdach', 'Fluessigkunststoff grob pro m2', 'Fluessigkunststoff Abdichtung grau 5 kg', 'kg', 'area', 0.5, null, true, 60),
    ('flachdach_dachablauf', 'flachdach', 'Dachablaeufe aus Durchdringungen', 'Dachablauf senkrecht DN 100', 'Stueck', 'penetrations_count', 1, null, true, 70),
    ('flachdach_notueberlauf', 'flachdach', 'Notueberlaeufe aus Durchdringungen', 'Notueberlauf Rechteck Edelstahl', 'Stueck', 'penetrations_count', 0.5, null, true, 80),
    ('flachdach_attikaabdeckung', 'flachdach', 'Attikaabdeckung aus Wandanschlusslaenge', 'Attikaabdeckung Aluminium 500 mm', 'm', 'wall_connection_length', 1, null, true, 90),

    ('entwaesserung_dachrinne', 'entwaesserung', 'Dachrinne aus Trauflaenge', 'Dachrinne halbrund RG 333 Zink', 'm', 'eaves_length', 1, null, true, 10),
    ('entwaesserung_rinnenhalter', 'entwaesserung', 'Rinnenhalter alle 60 cm', 'Rinnenhalter RG 333 verzinkt lang', 'Stueck', 'gutter_hangers', 1, 0.6, true, 20),
    ('entwaesserung_fallrohr', 'entwaesserung', 'Fallrohr aus Wand-/Fallrohrlaenge', 'Fallrohr DN 100 Zink', 'm', 'wall_connection_length', 1, null, true, 30),
    ('entwaesserung_rohrschellen', 'entwaesserung', 'Rohrschellen pro Meter', 'Rohrschelle DN 100 Zink mit Schlagstift', 'Stueck', 'wall_connection_length', 1, null, true, 40),

    ('blech_traufblech', 'blech', 'Traufblech aus Laenge', 'Traufblech Zink 200 mm', 'm', 'eaves_length', 1, null, true, 10),
    ('blech_kehlblech', 'blech', 'Kehlblech aus Laenge', 'Kehlblech Zink 500 mm', 'm', 'valley_length', 1, null, true, 20),
    ('blech_wandanschlussprofil', 'blech', 'Wandanschlussprofil aus Laenge', 'Wandanschlussprofil Aluminium', 'm', 'wall_connection_length', 1, null, true, 30),
    ('blech_kappleiste', 'blech', 'Kappleiste aus Laenge', 'Kappleiste Aluminium gelocht', 'm', 'wall_connection_length', 1, null, true, 40),

    ('reparatur_unterspannbahn', 'reparatur', 'Unterspannbahn Reparaturflaeche', 'Unterspannbahn diffusionsoffen 160 g', 'm2', 'area', 1, null, true, 10),
    ('reparatur_ersatzpfanne', 'reparatur', 'Ersatzpfannen grob pro m2', 'Ersatzpfanne universal Kunststoff', 'Stueck', 'area', 4, null, true, 20),
    ('reparatur_dichtstoff', 'reparatur', 'Dichtstoff fuer Anschluesse', 'PU Dichtstoff grau Kartusche', 'Stueck', 'wall_connection_length', 0.2, null, true, 30)
)
insert into public.material_calculation_rules (
  company_id,
  rule_key,
  roof_type,
  name,
  material_name,
  catalog_item_id,
  unit,
  calculation_method,
  factor,
  spacing_m,
  waste_applies,
  sort_order
)
select
  null,
  r.rule_key,
  r.roof_type,
  r.name,
  r.material_name,
  mc.id,
  r.unit,
  r.calculation_method,
  r.factor,
  r.spacing_m,
  r.waste_applies,
  r.sort_order
from rule_rows r
left join public.material_catalog mc on mc.name = r.material_name
on conflict (rule_key) where company_id is null do update set
  roof_type = excluded.roof_type,
  name = excluded.name,
  material_name = excluded.material_name,
  catalog_item_id = excluded.catalog_item_id,
  unit = excluded.unit,
  calculation_method = excluded.calculation_method,
  factor = excluded.factor,
  spacing_m = excluded.spacing_m,
  waste_applies = excluded.waste_applies,
  sort_order = excluded.sort_order,
  active = true;
