-- 20260622_rls_consolidation.sql
-- Konsolidiert automatisch als exakt redundant erkannte Redteam-Fallback-Policies.
-- Sicherheitsregel: Nur Policies aus scripts/audit-rls-policies.mjs --redundant-drops werden entfernt.
-- Die Tabelle wird vor jedem DROP geprueft, damit aeltere Supabase-Projekte mit fehlenden neueren Tabellen nicht abbrechen.

-- Automatisch erzeugt mit: node scripts/audit-rls-policies.mjs --redundant-drops
-- Entfernt nur Fallback-Policies, deren Bedingung exakt von einer spezifischen Policy gleicher Operation gedeckt ist.
do $$
declare
  redundant_policy record;
begin
  for redundant_policy in
    select *
    from (
      values
    ('public', 'ai_job_drafts', 'redteam managers select fallback', 'select', 'managers read ai job drafts'),
    ('public', 'ai_job_drafts', 'redteam managers update fallback', 'update', 'managers update ai job drafts'),
    ('public', 'ai_settings', 'redteam managers insert fallback', 'insert', 'managers insert ai settings'),
    ('public', 'ai_settings', 'redteam managers update fallback', 'update', 'managers update ai settings'),
    ('public', 'ai_usage_logs', 'redteam managers select fallback', 'select', 'managers read ai usage logs'),
    ('public', 'bring_list_availability_snapshots', 'redteam managers delete fallback', 'delete', 'managers delete availability snapshots'),
    ('public', 'bring_list_availability_snapshots', 'redteam managers update fallback', 'update', 'managers maintain availability snapshots'),
    ('public', 'bring_lists', 'redteam managers delete fallback', 'delete', 'managers delete bring lists'),
    ('public', 'calculation_settings', 'redteam managers select fallback', 'select', 'managers read calculation settings'),
    ('public', 'commercial_document_items', 'redteam managers delete fallback', 'delete', 'managers delete commercial document items'),
    ('public', 'commercial_document_items', 'redteam managers insert fallback', 'insert', 'managers insert commercial document items'),
    ('public', 'commercial_document_items', 'redteam managers select fallback', 'select', 'managers read commercial document items'),
    ('public', 'commercial_document_items', 'redteam managers update fallback', 'update', 'managers update commercial document items'),
    ('public', 'commercial_documents', 'redteam managers insert fallback', 'insert', 'managers insert commercial documents'),
    ('public', 'commercial_documents', 'redteam managers select fallback', 'select', 'managers read commercial documents'),
    ('public', 'commercial_documents', 'redteam managers update fallback', 'update', 'managers update commercial documents'),
    ('public', 'company_audit_log', 'redteam managers insert fallback', 'insert', 'managers create company audit log'),
    ('public', 'company_audit_log', 'redteam managers select fallback', 'select', 'managers read company audit log'),
    ('public', 'company_pricing_settings', 'redteam managers insert fallback', 'insert', 'managers can insert pricing settings'),
    ('public', 'company_pricing_settings', 'redteam managers select fallback', 'select', 'managers can read pricing settings'),
    ('public', 'company_pricing_settings', 'redteam managers update fallback', 'update', 'managers can update pricing settings'),
    ('public', 'customer_documents', 'redteam managers select fallback', 'select', 'managers read customer documents'),
    ('public', 'customer_portal_events', 'redteam managers select fallback', 'select', 'managers read customer portal events'),
    ('public', 'customer_portal_messages', 'redteam managers delete fallback', 'delete', 'managers delete customer portal messages'),
    ('public', 'customer_portal_messages', 'redteam managers insert fallback', 'insert', 'managers insert customer portal messages'),
    ('public', 'customer_portal_messages', 'redteam managers select fallback', 'select', 'managers read customer portal messages'),
    ('public', 'customer_portal_messages', 'redteam managers update fallback', 'update', 'managers update customer portal messages'),
    ('public', 'customer_portal_tokens', 'redteam managers delete fallback', 'delete', 'managers delete customer portal tokens'),
    ('public', 'customer_portal_tokens', 'redteam managers insert fallback', 'insert', 'managers insert customer portal tokens'),
    ('public', 'customer_portal_tokens', 'redteam managers select fallback', 'select', 'managers read customer portal tokens'),
    ('public', 'customer_portal_tokens', 'redteam managers update fallback', 'update', 'managers update customer portal tokens'),
    ('public', 'customers', 'redteam managers insert fallback', 'insert', 'managers can insert customers'),
    ('public', 'customers', 'redteam managers select fallback', 'select', 'managers can read customers'),
    ('public', 'customers', 'redteam managers update fallback', 'update', 'managers can update customers'),
    ('public', 'inventory_items', 'redteam managers insert fallback', 'insert', 'managers can insert inventory items'),
    ('public', 'inventory_items', 'redteam managers select fallback', 'select', 'managers can read inventory items with prices'),
    ('public', 'inventory_items', 'redteam managers update fallback', 'update', 'managers can update inventory items'),
    ('public', 'inventory_locations', 'redteam managers delete fallback', 'delete', 'managers can delete inventory locations'),
    ('public', 'inventory_locations', 'redteam managers insert fallback', 'insert', 'managers can insert inventory locations'),
    ('public', 'inventory_locations', 'redteam managers select fallback', 'select', 'read own company inventory locations'),
    ('public', 'inventory_locations', 'redteam managers update fallback', 'update', 'managers can update inventory locations'),
    ('public', 'job_dimensions', 'redteam managers insert fallback', 'insert', 'managers can insert job dimensions'),
    ('public', 'job_dimensions', 'redteam managers update fallback', 'update', 'managers can update job dimensions'),
    ('public', 'job_estimates', 'redteam managers insert fallback', 'insert', 'managers create job estimates'),
    ('public', 'job_estimates', 'redteam managers select fallback', 'select', 'managers read job estimates'),
    ('public', 'job_material_calculation_items', 'redteam managers delete fallback', 'delete', 'managers can delete calculation items'),
    ('public', 'job_material_calculation_items', 'redteam managers insert fallback', 'insert', 'managers can insert calculation items'),
    ('public', 'job_material_calculation_items', 'redteam managers select fallback', 'select', 'managers can read priced calculation items'),
    ('public', 'job_material_calculation_items', 'redteam managers update fallback', 'update', 'managers can update calculation items'),
    ('public', 'job_material_calculations', 'redteam managers delete fallback', 'delete', 'managers can delete job material calculations'),
    ('public', 'job_material_calculations', 'redteam managers insert fallback', 'insert', 'managers can insert job material calculations'),
    ('public', 'job_material_calculations', 'redteam managers update fallback', 'update', 'managers can update job material calculations'),
    ('public', 'job_material_requirements', 'redteam managers insert fallback', 'insert', 'managers can insert order requirements'),
    ('public', 'job_material_requirements', 'redteam managers select fallback', 'select', 'managers can read priced order requirements'),
    ('public', 'job_material_requirements', 'redteam managers update fallback', 'update', 'managers can update order requirements'),
    ('public', 'jobsite_activity_events', 'redteam managers update fallback', 'update', 'managers archive jobsite activity'),
    ('public', 'jobsite_documents', 'redteam managers update fallback', 'update', 'managers update jobsite documents'),
    ('public', 'jobsites', 'redteam managers insert fallback', 'insert', 'managers can insert jobsites'),
    ('public', 'jobsites', 'redteam managers update fallback', 'update', 'managers can update jobsites'),
    ('public', 'material_alerts', 'redteam managers update fallback', 'update', 'managers update material alerts'),
    ('public', 'material_calculation_rules', 'redteam managers delete fallback', 'delete', 'managers can delete calculation rules'),
    ('public', 'material_calculation_rules', 'redteam managers insert fallback', 'insert', 'managers can insert calculation rules'),
    ('public', 'material_calculation_rules', 'redteam managers update fallback', 'update', 'managers can update calculation rules'),
    ('public', 'material_movements', 'redteam managers insert fallback', 'insert', 'managers create material movements'),
    ('public', 'material_movements', 'redteam managers update fallback', 'update', 'managers update material movements'),
    ('public', 'material_reservations', 'redteam managers insert fallback', 'insert', 'managers create material reservations'),
    ('public', 'material_reservations', 'redteam managers update fallback', 'update', 'managers update material reservations'),
    ('public', 'materials', 'redteam managers insert fallback', 'insert', 'managers can insert materials'),
    ('public', 'materials', 'redteam managers select fallback', 'select', 'managers can read materials with prices'),
    ('public', 'materials', 'redteam managers update fallback', 'update', 'managers can update materials'),
    ('public', 'online_price_discoveries', 'redteam managers delete fallback', 'delete', 'managers can delete online price discoveries'),
    ('public', 'online_price_discoveries', 'redteam managers insert fallback', 'insert', 'managers can insert online price discoveries'),
    ('public', 'online_price_discoveries', 'redteam managers select fallback', 'select', 'managers can read online price discoveries'),
    ('public', 'online_price_offers', 'redteam managers delete fallback', 'delete', 'managers can delete online price offers'),
    ('public', 'online_price_offers', 'redteam managers insert fallback', 'insert', 'managers can insert online price offers'),
    ('public', 'online_price_offers', 'redteam managers select fallback', 'select', 'managers can read online price offers'),
    ('public', 'order_measurement_items', 'redteam managers insert fallback', 'insert', 'managers insert order measurement items'),
    ('public', 'order_measurement_items', 'redteam managers select fallback', 'select', 'managers read order measurement items'),
    ('public', 'order_measurement_items', 'redteam managers update fallback', 'update', 'managers update order measurement items'),
    ('public', 'orders', 'redteam managers insert fallback', 'insert', 'managers can insert orders'),
    ('public', 'orders', 'redteam managers select fallback', 'select', 'managers can read orders'),
    ('public', 'orders', 'redteam managers update fallback', 'update', 'managers can update orders'),
    ('public', 'planning_assignments', 'redteam managers insert fallback', 'insert', 'managers insert planning assignments'),
    ('public', 'planning_assignments', 'redteam managers update fallback', 'update', 'managers update planning assignments'),
    ('public', 'planning_resources', 'redteam managers insert fallback', 'insert', 'managers insert planning resources'),
    ('public', 'planning_resources', 'redteam managers update fallback', 'update', 'managers update planning resources'),
    ('public', 'planning_weather_checks', 'redteam managers insert fallback', 'insert', 'managers insert planning weather checks'),
    ('public', 'planning_weather_checks', 'redteam managers update fallback', 'update', 'managers update planning weather checks'),
    ('public', 'privacy_requests', 'redteam managers update fallback', 'update', 'managers update privacy requests'),
    ('public', 'profiles', 'redteam managers delete fallback', 'delete', 'managers can delete profiles'),
    ('public', 'profiles', 'redteam managers insert fallback', 'insert', 'managers can insert profiles'),
    ('public', 'profiles', 'redteam managers update fallback', 'update', 'managers can update profiles'),
    ('public', 'purchase_suggestions', 'redteam managers select fallback', 'select', 'managers read purchase suggestions'),
    ('public', 'purchase_suggestions', 'redteam managers update fallback', 'update', 'managers update purchase suggestions'),
    ('public', 'report_photos', 'redteam managers update fallback', 'update', 'managers update report photo release'),
    ('public', 'resource_documents', 'redteam managers insert fallback', 'insert', 'managers insert resource documents'),
    ('public', 'resource_documents', 'redteam managers update fallback', 'update', 'managers update resource documents'),
    ('public', 'supplier_integrations', 'redteam managers delete fallback', 'delete', 'managers can delete supplier integrations'),
    ('public', 'supplier_integrations', 'redteam managers insert fallback', 'insert', 'managers can insert supplier integrations'),
    ('public', 'supplier_integrations', 'redteam managers select fallback', 'select', 'managers can read supplier integrations'),
    ('public', 'supplier_integrations', 'redteam managers update fallback', 'update', 'managers can update supplier integrations'),
    ('public', 'supplier_offer_matches', 'redteam managers delete fallback', 'delete', 'managers can delete supplier offer matches'),
    ('public', 'supplier_offer_matches', 'redteam managers insert fallback', 'insert', 'managers can insert supplier offer matches'),
    ('public', 'supplier_offer_matches', 'redteam managers select fallback', 'select', 'managers can read supplier offer matches'),
    ('public', 'supplier_offer_matches', 'redteam managers update fallback', 'update', 'managers can update supplier offer matches'),
    ('public', 'supplier_offers', 'redteam managers delete fallback', 'delete', 'managers can delete supplier offers'),
    ('public', 'supplier_offers', 'redteam managers insert fallback', 'insert', 'managers can insert supplier offers'),
    ('public', 'supplier_offers', 'redteam managers select fallback', 'select', 'managers can read supplier offers'),
    ('public', 'supplier_offers', 'redteam managers update fallback', 'update', 'managers can update supplier offers'),
    ('public', 'supplier_price_history', 'redteam managers delete fallback', 'delete', 'managers can delete supplier price history'),
    ('public', 'supplier_price_history', 'redteam managers insert fallback', 'insert', 'managers can insert supplier price history'),
    ('public', 'supplier_price_history', 'redteam managers select fallback', 'select', 'managers can read supplier price history'),
    ('public', 'suppliers', 'redteam managers delete fallback', 'delete', 'managers can delete suppliers'),
    ('public', 'suppliers', 'redteam managers insert fallback', 'insert', 'managers can insert suppliers'),
    ('public', 'suppliers', 'redteam managers select fallback', 'select', 'read own company suppliers'),
    ('public', 'suppliers', 'redteam managers update fallback', 'update', 'managers can update suppliers'),
    ('public', 'tasks', 'redteam managers insert fallback', 'insert', 'managers can insert tasks'),
    ('public', 'time_reports', 'redteam managers delete fallback', 'delete', 'managers can delete time reports'),
    ('public', 'time_reports', 'redteam managers insert fallback', 'insert', 'managers can insert time reports'),
    ('public', 'time_reports', 'redteam managers select fallback', 'select', 'managers can read time reports'),
    ('public', 'time_reports', 'redteam managers update fallback', 'update', 'managers can update time reports'),
    ('public', 'vehicle_materials', 'redteam managers insert fallback', 'insert', 'managers can insert vehicle materials'),
    ('public', 'vehicle_materials', 'redteam managers update fallback', 'update', 'managers can update vehicle materials'),
    ('public', 'vehicles', 'redteam managers insert fallback', 'insert', 'managers can insert vehicles'),
    ('public', 'vehicles', 'redteam managers update fallback', 'update', 'managers can update vehicles'),
    ('public', 'weather_snapshots', 'redteam managers delete fallback', 'delete', 'managers can delete weather snapshots'),
    ('public', 'weather_snapshots', 'redteam managers insert fallback', 'insert', 'managers can insert weather snapshots'),
    ('public', 'weather_snapshots', 'redteam managers select fallback', 'select', 'managers can read weather snapshots'),
    ('public', 'weather_snapshots', 'redteam managers update fallback', 'update', 'managers can update weather snapshots'),
    ('public', 'work_order_versions', 'redteam managers insert fallback', 'insert', 'managers insert work order versions'),
    ('public', 'work_order_versions', 'redteam managers select fallback', 'select', 'managers read work order versions'),
    ('public', 'work_orders', 'redteam managers insert fallback', 'insert', 'managers insert work orders'),
    ('public', 'work_orders', 'redteam managers select fallback', 'select', 'managers read work orders'),
    ('public', 'work_orders', 'redteam managers update fallback', 'update', 'managers update work orders')
    ) as policy_drop(schema_name, table_name, policy_name, operation_name, covered_by_policy)
  loop
    if to_regclass(format('%I.%I', redundant_policy.schema_name, redundant_policy.table_name)) is not null then
      execute format(
        'drop policy if exists %I on %I.%I',
        redundant_policy.policy_name,
        redundant_policy.schema_name,
        redundant_policy.table_name
      );
    end if;
  end loop;
end $$;

notify pgrst, 'reload schema';
